services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./lua:/lua # Mount the local lua directory to the container's /lua directory
