name: Publish Docker Image

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build . --tag ghcr.io/lcox74/driftwood:latest
          docker tag ghcr.io/lcox74/driftwood:latest ghcr.io/lcox74/driftwood:${{ github.ref_name }}
          docker push ghcr.io/lcox74/driftwood:latest
          docker push ghcr.io/lcox74/driftwood:${{ github.ref_name }}
